#############################################################################
# Makefile for building: complex
# Generated by qmake (2.01a) (Qt 4.8.3) on: Tue Mar 21 19:57:18 2017
# Project:  complex.pro
# Template: subdirs
# Command: /usr/local/qt4.8_arm/bin/qmake -o Makefile complex.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/local/qt4.8_arm/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-src \
		sub-app

src/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /mnt/hgfs/Winshare/cc_folder/src/src.pro -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /mnt/hgfs/Winshare/cc_folder/src/src.pro -o $(MAKEFILE)
sub-src: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_default: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-make_first: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-all-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-all: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-clean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-distclean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-install_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-src-uninstall_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall
app/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) app/ || $(MKDIR) app/ 
	cd app/ && $(QMAKE) /mnt/hgfs/Winshare/cc_folder/app/app.pro -o $(MAKEFILE)
sub-app-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) app/ || $(MKDIR) app/ 
	cd app/ && $(QMAKE) /mnt/hgfs/Winshare/cc_folder/app/app.pro -o $(MAKEFILE)
sub-app: app/$(MAKEFILE) FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE)
sub-app-make_default-ordered: app/$(MAKEFILE) sub-src-make_default-ordered  FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) 
sub-app-make_default: app/$(MAKEFILE) FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) 
sub-app-make_first-ordered: app/$(MAKEFILE) sub-src-make_first-ordered  FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) first
sub-app-make_first: app/$(MAKEFILE) FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) first
sub-app-all-ordered: app/$(MAKEFILE) sub-src-all-ordered  FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) all
sub-app-all: app/$(MAKEFILE) FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) all
sub-app-clean-ordered: app/$(MAKEFILE) sub-src-clean-ordered  FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) clean
sub-app-clean: app/$(MAKEFILE) FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) clean
sub-app-distclean-ordered: app/$(MAKEFILE) sub-src-distclean-ordered  FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) distclean
sub-app-distclean: app/$(MAKEFILE) FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) distclean
sub-app-install_subtargets-ordered: app/$(MAKEFILE) sub-src-install_subtargets-ordered  FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) install
sub-app-install_subtargets: app/$(MAKEFILE) FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) install
sub-app-uninstall_subtargets-ordered: app/$(MAKEFILE) sub-src-uninstall_subtargets-ordered  FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-app-uninstall_subtargets: app/$(MAKEFILE) FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: complex.pro  /usr/local/qt4.8_arm/mkspecs/qws/linux-arm-g++/qmake.conf /usr/local/qt4.8_arm/mkspecs/common/unix.conf \
		/usr/local/qt4.8_arm/mkspecs/common/linux.conf \
		/usr/local/qt4.8_arm/mkspecs/common/gcc-base.conf \
		/usr/local/qt4.8_arm/mkspecs/common/gcc-base-unix.conf \
		/usr/local/qt4.8_arm/mkspecs/common/g++-base.conf \
		/usr/local/qt4.8_arm/mkspecs/common/g++-unix.conf \
		/usr/local/qt4.8_arm/mkspecs/common/qws.conf \
		/usr/local/qt4.8_arm/mkspecs/qconfig.pri \
		/usr/local/qt4.8_arm/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/qt4.8_arm/mkspecs/features/qt_functions.prf \
		/usr/local/qt4.8_arm/mkspecs/features/qt_config.prf \
		/usr/local/qt4.8_arm/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt4.8_arm/mkspecs/features/default_pre.prf \
		/usr/local/qt4.8_arm/mkspecs/features/release.prf \
		/usr/local/qt4.8_arm/mkspecs/features/default_post.prf \
		/usr/local/qt4.8_arm/mkspecs/features/warn_on.prf \
		/usr/local/qt4.8_arm/mkspecs/features/qt.prf \
		/usr/local/qt4.8_arm/mkspecs/features/unix/thread.prf \
		/usr/local/qt4.8_arm/mkspecs/features/moc.prf \
		/usr/local/qt4.8_arm/mkspecs/features/resources.prf \
		/usr/local/qt4.8_arm/mkspecs/features/uic.prf \
		/usr/local/qt4.8_arm/mkspecs/features/yacc.prf \
		/usr/local/qt4.8_arm/mkspecs/features/lex.prf \
		/usr/local/qt4.8_arm/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile complex.pro
/usr/local/qt4.8_arm/mkspecs/common/unix.conf:
/usr/local/qt4.8_arm/mkspecs/common/linux.conf:
/usr/local/qt4.8_arm/mkspecs/common/gcc-base.conf:
/usr/local/qt4.8_arm/mkspecs/common/gcc-base-unix.conf:
/usr/local/qt4.8_arm/mkspecs/common/g++-base.conf:
/usr/local/qt4.8_arm/mkspecs/common/g++-unix.conf:
/usr/local/qt4.8_arm/mkspecs/common/qws.conf:
/usr/local/qt4.8_arm/mkspecs/qconfig.pri:
/usr/local/qt4.8_arm/mkspecs/modules/qt_webkit_version.pri:
/usr/local/qt4.8_arm/mkspecs/features/qt_functions.prf:
/usr/local/qt4.8_arm/mkspecs/features/qt_config.prf:
/usr/local/qt4.8_arm/mkspecs/features/exclusive_builds.prf:
/usr/local/qt4.8_arm/mkspecs/features/default_pre.prf:
/usr/local/qt4.8_arm/mkspecs/features/release.prf:
/usr/local/qt4.8_arm/mkspecs/features/default_post.prf:
/usr/local/qt4.8_arm/mkspecs/features/warn_on.prf:
/usr/local/qt4.8_arm/mkspecs/features/qt.prf:
/usr/local/qt4.8_arm/mkspecs/features/unix/thread.prf:
/usr/local/qt4.8_arm/mkspecs/features/moc.prf:
/usr/local/qt4.8_arm/mkspecs/features/resources.prf:
/usr/local/qt4.8_arm/mkspecs/features/uic.prf:
/usr/local/qt4.8_arm/mkspecs/features/yacc.prf:
/usr/local/qt4.8_arm/mkspecs/features/lex.prf:
/usr/local/qt4.8_arm/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile complex.pro

qmake_all: sub-src-qmake_all sub-app-qmake_all FORCE

make_default: sub-src-make_default-ordered sub-app-make_default-ordered FORCE
make_first: sub-src-make_first-ordered sub-app-make_first-ordered FORCE
all: sub-src-all-ordered sub-app-all-ordered FORCE
clean: sub-src-clean-ordered sub-app-clean-ordered FORCE
distclean: sub-src-distclean-ordered sub-app-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets-ordered sub-app-install_subtargets-ordered FORCE
uninstall_subtargets: sub-src-uninstall_subtargets-ordered sub-app-uninstall_subtargets-ordered FORCE

sub-src-check_ordered: src/$(MAKEFILE)
	cd src/ && $(MAKE) -f $(MAKEFILE) check
sub-app-check_ordered: app/$(MAKEFILE) sub-src-check_ordered 
	cd app/ && $(MAKE) -f $(MAKEFILE) check
check: sub-src-check_ordered sub-app-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

